server:
  port: 9000
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/graduation?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.43.10
  rabbitmq:
    host: 192.168.43.10